// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsd2fSYbX3dNmffaXYmiLSxgep0cHz0a8',
    appId: '1:89344993937:web:fe24abfb681d63566f2d30',
    messagingSenderId: '89344993937',
    projectId: 'al-qaim-petroleum',
    authDomain: 'al-qaim-petroleum.firebaseapp.com',
    storageBucket: 'al-qaim-petroleum.firebasestorage.app',
    measurementId: 'G-L2YR4CSR71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwVgdmtKdqIgqH_FLoMNJ0R9ittByLoIw',
    appId: '1:89344993937:android:e782103a8b11c0736f2d30',
    messagingSenderId: '89344993937',
    projectId: 'al-qaim-petroleum',
    storageBucket: 'al-qaim-petroleum.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsd2fSYbX3dNmffaXYmiLSxgep0cHz0a8',
    appId: '1:89344993937:web:10b07fa8c2963f766f2d30',
    messagingSenderId: '89344993937',
    projectId: 'al-qaim-petroleum',
    authDomain: 'al-qaim-petroleum.firebaseapp.com',
    storageBucket: 'al-qaim-petroleum.firebasestorage.app',
    measurementId: 'G-F4D9R4LWPR',
  );
}
